name: Publish Gem
on:
  workflow_dispatch:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.2
      - name: Bundle Setup
        run: |
          gem update --system 3.1.4 -N
          gem install --no-document bundler
          bundle config path ${{ github.workspace }}/vendor/bundle
      - name: Bundle Install
        run: |
          bundle install --jobs 4 --retry 3
      - name: Set Credentials
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
      - name: Publish to Rubygems
        run: |
          export OWNER=$( echo ${{ github.repository }} | cut -d "/" -f 1 )
          gem build school_declare.gemspec
          gem push *.gem
